version: '3.2'
# user: neo4j, password: admin
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.2
    volumes:
      - source: ./config/logstash/pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#  artemis:
#    image: vromero/activemq-artemis:2.16.0-alpine
#    environment:
#      - "DISABLE_SECURITY=true"
#    ports:
#      - "61616:61616"
#      - "8161:8161"

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  neo4j:
    image: 'neo4j:4.2'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
      # ports for remote backup
      - '6362:6362'
    volumes:
     - './neo4j/data:/data'
     - './neo4j/conf:/conf'
     - './neo4j/logs:/logs'
     - './neo4j/metrics:/metrics'
     - './neo4j/import:/import'
     - './neo4j/plugins:/plugins'
    environment:
     - NEO4J_AUTH=none
# "graph-algorithms", "streams", "graphql"
#     - NEO4JLABS_PLUGINS=["apoc"]
