spring:
  application.name: depcare-crawler
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.appga.depcare: INFO
    edu.uci.ics.crawler4j: WARN

depcare:
  crawler:
    numOfCrawlers: 4
  parentProjectsOnly: false

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web.exposure.include: health,info,prometheus,metrics
  metrics.export.prometheus.enabled: true
